/**:
    # Using broad URI to share common parameters
    ros__parameters:
        # Scan2Grid parameters
        map_resolution: 0.1
        map_width: 200
        map_height: 200

        # PathPlanner parameters
        use_path_optimizer: false
        safety_distance: 0.4

        # Explorer parameters
        reached_dist_thresh: 0.2
        navigation_speed: 0.5
        # safety_distance: 0.4

        # FrontierAllocator parameters
        frontier_min_area: 15
        frontier_max_area: 35
        # safety_distance: 0.4